export const fourTrainingsDayProgram = {
    week1: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week2: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week3: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week4: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week5: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week6: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week7: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week8: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week9: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week10: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week11: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week12: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
};

export const fiveTrainingsDayProgram = {
    week1: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week2: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week3: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week4: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week5: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week6: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week7: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week8: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week9: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week10: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week11: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week12: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
};

export const sixTrainingsDayProgram = {
    week1: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week2: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week3: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week4: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week5: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week6: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week7: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week8: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week9: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week10: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week11: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
    week12: [
        { type: 'mediumRun', time: '50:00' },
        { type: 'intervalsRun', warmUpTime: '30:00', repetition: 7, distance: 400, recupTime: '1:30' },
        { type: 'mediumRun', time: '60:00' },
        { type: 'mediumRun', time: '75:00' },
        { type: 'mediumRun', time: '75:00' },
    ],
};
