export const fourTrainingsDayProgram = {
    week1: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week2: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week3: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week4: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week5: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week6: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week7: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week8: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week9: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week10: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week11: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week12: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
    ],
};

export const fiveTrainingsDayProgram = {
    week1: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week2: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week3: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week4: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week5: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week6: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week7: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week8: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week9: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week10: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week11: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week12: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
};

export const sixTrainingsDayProgram = {
    week1: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week2: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week3: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week4: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week5: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week6: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week7: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week8: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week9: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week10: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week11: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
    week12: [
        { type: 'mediumRun', time: '50"' },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: '60"' },
        { type: 'mediumRun', time: '75"' },
        { type: 'mediumRun', time: '75"' },
    ],
};
