export const fourTrainingsDayProgram = {
    week1: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: "30'", repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'longRun', time: "75'" },
    ],
    week2: [
        { type: 'mediumRun', time: "50'" },
        {
            type: 'intervalsRun',
            warmUpTime: "30'",
            repetition: 2,
            intervalsRepetition: 6,
            time1: '30"',
            time2: '30"',
            recupTime: "4'",
        },
        { type: 'mediumRun', time: "60'" },
        { type: 'longRun', time: "80'" },
    ],
    week3: [
        { type: 'mediumRun', time: "60'" },
        { type: 'thresholdRun', warmUpTime: "30'", repetition: 7, distance: 700, recupTime: '2\'30"' },
        { type: 'thresholdRun', warmUpTime: "30'", repetition: 8, distance: 200, recupTime: '2\'30"' },
        { type: 'longRun', time: "90'" },
    ],
    week4: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: "30'", repetition: 6, distance: 900, recupTime: "3'" },
        { type: 'mediumRun', time: "50'" },
        { type: 'longRun', time: "85'" },
    ],
    week5: [
        { type: 'mediumRun', time: "60'" },
        { type: 'thresholdRun', warmUpTime: "1H05'", details: "4x4'ALLURE MARATHON", recupTime: "2'" },
        { type: 'mediumRun', time: "60'" },
        { type: 'longRun', time: "95'" },
    ],
    week6: [
        { type: 'thresholdRun', warmUpTime: "30'", repetition: 7, distance: 400, recupTime: '2\'30"' },
        { type: 'thresholdRun', warmUpTime: '45', repetition: 3, distance: 1400, recupTime: "3'" },
        { type: 'mediumRun', time: "50'" },
        { type: 'longRun', time: "110'" },
    ],
    week7: [
        { type: 'mediumRun', time: "50'" },
        {
            type: 'intervalsRun',
            warmUpTime: "30'",
            repetition: 2,
            intervalsRepetition: 5,
            time1: '60"',
            time2: '60"',
            recupTime: "4'",
        },
        { type: 'mediumRun', time: "45'" },
        { type: 'mediumRun', time: "1H40'" },
    ],
    week8: [
        { type: 'mediumRun', time: "60'" },
        { type: 'thresholdRun', warmUpTime: '45', repetition: 3, distance: 1400, recupTime: "3'" },
        { type: 'mediumRun', time: "60'" },
        { type: 'longRun', time: "100'" },
    ],
    week9: [
        {
            type: 'intervalsRun',
            warmUpTime: "30'",
            repetition: 2,
            intervalsRepetition: 9,
            time1: '20"',
            time2: '20"',
            recupTime: "4'",
        },
        {
            type: 'thresholdRun',
            warmUpTime: "40'",
            repetition: 3,
            distance: 2000,
            recupTime: "3'",
        },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "50'" },
    ],
    week10: [
        {
            type: 'thresholdRun',
            warmUpTime: "30'",
            repetition: 6,
            distance: 900,
            recupTime: "3'",
        },
        {
            type: 'thresholdRun',
            warmUpTime: "45'",
            repetition: 2,
            distance: 3000,
            recupTime: "4'",
        },
        { type: 'mediumRun', time: "60'" },
        { type: 'longRun', time: "120'" },
    ],
    week11: [
        { type: 'mediumRun', time: "60'" },
        {
            type: 'thresholdRun',
            warmUpTime: "40'",
            repetition: 6,
            distance: 1000,
            recupTime: "2'",
        },
        { type: 'longRun', time: "95'" },
        { type: 'mediumRun', time: "35'" },
    ],
    week12: [
        {
            type: 'intervalsRun',
            warmUpTime: "30'",
            repetition: 2,
            intervalsRepetition: 5,
            time1: '60"',
            time2: '60"',
            recupTime: "4'",
        },
        {
            type: 'mediumRun',
            time: "40'",
        },
        { type: 'mediumRun', time: "30'" },
        { type: 'marathon', time: '3H45\'00"' },
    ],
};

export const fiveTrainingsDayProgram = {
    week1: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week2: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week3: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week4: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week5: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week6: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week7: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week8: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week9: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week10: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week11: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week12: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
};

export const sixTrainingsDayProgram = {
    week1: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week2: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week3: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week4: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week5: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week6: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week7: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week8: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week9: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week10: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week11: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
    week12: [
        { type: 'mediumRun', time: "50'" },
        { type: 'thresholdRun', warmUpTime: '30"', repetition: 7, distance: 400, recupTime: '1\'30"' },
        { type: 'mediumRun', time: "60'" },
        { type: 'mediumRun', time: "75'" },
        { type: 'mediumRun', time: "75'" },
    ],
};
